name: SMAX Unit Tests (Linux, Mac)

on: [push]

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 9
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        redis-version: [latest]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pip install SMAX package
        run: pip3 install .

      - name: Setup redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ matrix.redis-version }}
          auto-start: "true"
          redis-conf: |
            bind 127.0.0.1
            protected-mode no


      - name: Load LUA scripts
        run: |
          cd redis_config_files
          ./smax-init.sh

      - name: Test with pytest
        run: |
          cd ..
          pytest -v -x --log-level=DEBUG
