name: SMAX Unit Tests (Windowsß)

on: [push]

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 9
      matrix:
        os: [windows-latest]
        python-version: [3.7, 3.8, 3.9]
        redis-version: [5.0.3]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pip install SMAX package
        run: pip3 install . --use-feature=in-tree-build

      - name: Setup redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ matrix.redis-version }}
          auto-start: "true"

      - name: Load LUA scripts
        run: |
          cd redis_config_files
          ./initscripts.sh

      - name: Test with pytest
        run: |
          cd ..
          pytest