name: Start SMAX and run pytest

on: [push]

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: smax
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false

      - name: Start Redis
        run: redis-server ./redis_config_files/redis.conf &

      - name: Load LUA scripts
        run: |
          cd redis_config_files
          ./initscripts.sh

      - name: Test with pytest
        run: |
          cd ..
          pytest