name: Start SMAX and run pytest

on: [push]

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 9
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
        redis-version: [5]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pip install SMAX package
        run: pip install .

      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Load LUA scripts
        run: |
          cd redis_config_files
          ./initscripts.sh

      - name: Test with pytest
        run: |
          cd ..
          pytest